using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace LauraStuffs
{
    class CRUDGenerator
    {
        public static void Generate(string namespaceName, string dirName)
        {
            //Get the current assembly
            Assembly assembly = Assembly.GetExecutingAssembly();

            //Uses reflection to get all the types inside the namespace given
            Type[] types = assembly.GetTypes()
              .Where(t => String.Equals(t.Namespace, namespaceName, StringComparison.Ordinal))
              .ToArray();

            //Checks if it found any types
            if (types != null && types.Any())
            {
                //Character tab, for indent the code
                string tab = "\t";

                //Create the directory if does not exists
                Directory.CreateDirectory(dirName);

                //Loops through all types found in the namespace given
                //I assuming that the first type is the data context generated by Linq to SQL
                for (int i = 1; i < types.Length; i++)
                {
                    //This will write the code into a string so we can save it later
                    StringBuilder sb = new StringBuilder();

                    //All the references used by the code
                    sb.AppendLine("using System;");
                    sb.AppendLine("using System.Collections.Generic;");
                    sb.AppendLine("using System.Linq;");
                    sb.AppendLine("using System.Text;");
                    sb.AppendLine("using System.Threading.Tasks;");
                    sb.AppendLine("using LauraStuffs;");

                    //It creates its own namespace adding the word CRUD after the namespace given
                    sb.AppendLine("namespace " + namespaceName + ".CRUD");
                    sb.AppendLine("{ ");
                    sb.AppendLine(tab + "class model_" + types[i].Name);
                    sb.AppendLine(tab + "{");

                    //This vars will help build the params to the Create and Update functions
                    string param = "";
                    string queryCondition = "";
                    string objName = types[i].Name + "OBJ";
                    StringBuilder sbProperties = new StringBuilder();
                    PropertyInfo[] proper = types[i].GetProperties();

                    //Loops through all atributes of the types
                    foreach (var prop in proper)
                    {
                        if (prop.Name != "id_" && prop.PropertyType.Namespace != namespaceName && prop.PropertyType.FullName.IndexOf("entity", StringComparison.InvariantCultureIgnoreCase) < 0)
                        {
                            string propType = "string";

                            //This checks what type the atribute is, looking for common types used in the data base
                            if (!prop.PropertyType.FullName.Contains("string"))
                            {
                                if (prop.PropertyType.FullName.IndexOf("bool", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "bool";
                                else if (prop.PropertyType.FullName.IndexOf("byte", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "byte";
                                else if (prop.PropertyType.FullName.IndexOf("int", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "int";
                                else if (prop.PropertyType.FullName.IndexOf("double", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "double";
                                else if (prop.PropertyType.FullName.IndexOf("decimal", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "decimal";
                                else if (prop.PropertyType.FullName.IndexOf("binary", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "binary";
                                else if (prop.PropertyType.FullName.IndexOf("DateTime", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "DateTime";
                                else if (prop.PropertyType.FullName.IndexOf("TimeSpan", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "TimeSpan";
                                else if (prop.PropertyType.FullName.IndexOf("DateTimeOffset", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "DateTimeOffset";
                                else if (prop.PropertyType.FullName.IndexOf("Guid", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "Guid";
                                else if (prop.PropertyType.FullName.IndexOf("char", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType = "char";

                                if (prop.PropertyType.FullName.IndexOf("null", StringComparison.InvariantCultureIgnoreCase) >= 0)
                                    propType += "?";
                            }

                            param += propType + " " + prop.Name + ", ";
                            queryCondition += "new QueryConditions(" + prop.Name + ", OperatorComparer.Equals, \"" + prop.Name + "\"), ";
                            sbProperties.AppendLine(tab + tab + tab + tab + tab + objName + "." + prop.Name + " = " + prop.Name + ";");
                        }
                    }

                    //Write a auxiliar params code to be useed further
                    param = param.Substring(0, param.Length - 2);
                    queryCondition = queryCondition.Substring(0, queryCondition.Length - 2);
                    param += ")";
                    queryCondition += ")";

                    //Writes the CREATE function
                    sb.AppendLine(tab + tab + "static public " + namespaceName + "." + types[i].Name + " Create(" + param);
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + namespaceName + "." + types[i].Name + " " + objName + " = ReadWhereFirst(" + queryCondition + ";");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + "if (" + objName + " == null)");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + "try");
                    sb.AppendLine(tab + tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + tab + types[0].Name + " context = new " + types[0].Name + "();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + tab + objName + " = new " + namespaceName + "." + types[i].Name + "();");
                    sb.AppendLine("");
                    sb.AppendLine(sbProperties.ToString());
                    sb.AppendLine(tab + tab + tab + tab + tab + "context." + types[i].Name + ".InsertOnSubmit(" + objName + ");");
                    sb.AppendLine(tab + tab + tab + tab + tab + "context.SubmitChanges();");
                    sb.AppendLine(tab + tab + tab + tab + tab + "return " + objName + ";");
                    sb.AppendLine(tab + tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + tab + "catch (Exception error)");
                    sb.AppendLine(tab + tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + tab + "Console.WriteLine(\"EXCEPTION!!! \" + \"Classe: \" + \"mdl_" + types[i].Name + "\" + \" Metódo: \" + \"Create\");");
                    sb.AppendLine(tab + tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "return " + objName + ";");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine("");

                    //Writes the READ FIRST function
                    sb.AppendLine(tab + tab + "static public " + namespaceName + "." + types[i].Name + " ReadWhereFirst(params QueryConditions[] conditions)");
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + "IEnumerable<" + namespaceName + "." + types[i].Name + "> list = ReadAllWhere(conditions);");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + "if (list != null && list.Any())");
                    sb.AppendLine(tab + tab + tab + tab + "return list.First();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + "return null;");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine("");

                    //Writes the READ LAST function
                    sb.AppendLine(tab + tab + "static public " + namespaceName + "." + types[i].Name + " ReadWhereLast(params QueryConditions[] conditions)");
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + "IEnumerable<" + namespaceName + "." + types[i].Name + "> list = ReadAllWhere(conditions);");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + "if (list != null && list.Any())");
                    sb.AppendLine(tab + tab + tab + tab + "return list.Last();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + "return null;");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine("");

                    //Writes the READ ALL function
                    sb.AppendLine(tab + tab + "static public IEnumerable<" + namespaceName + "." + types[i].Name + "> ReadAllWhere(params QueryConditions[] conditions)");
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + "try");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + types[0].Name + " context = new " + types[0].Name + "();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "IQueryable <" + namespaceName + "." + types[i].Name + "> query = context." + types[i].Name + ";");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "foreach (QueryConditions q in conditions)");
                    sb.AppendLine(tab + tab + tab + tab + tab + "query = query.Where(ExpressionBuilder.BuildPredicate<" + types[i].Name + ">(q.value, q.comparer, q.properties));");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "if (query.Any())");
                    sb.AppendLine(tab + tab + tab + tab + tab + "return query;");
                    sb.AppendLine(tab + tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "catch (Exception erro)");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + "Console.WriteLine(\"EXCEPTION!!! \" + \"Classe: \" + \"mdl_" + types[i].Name + "\" + \" Metódo: \" + \"ReadAllWhere\");");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "return null;");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine("");

                    //Writes the UPDATE function
                    sb.AppendLine(tab + tab + "static public " + namespaceName + "." + types[i].Name + " Update(int id_, " + param);
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + "try");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + types[0].Name + " context = new " + types[0].Name + "();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "var query = from u in context." + types[i].Name + " where u.id_ == id_ select u;");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "if (query.Any())");
                    sb.AppendLine(tab + tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + tab + namespaceName + "." + types[i].Name + " " + objName + " = query.First();");
                    sb.AppendLine("");
                    sb.AppendLine(sbProperties.ToString());
                    sb.AppendLine(tab + tab + tab + tab + tab + "context.SubmitChanges();");
                    sb.AppendLine(tab + tab + tab + tab + tab + "return " + objName + ";");
                    sb.AppendLine(tab + tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "catch (Exception error)");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + "Console.WriteLine(\"EXCEPTION!!! \" + \"Classe: \" + \"mdl_" + types[i].Name + "\" + \" Metódo: \" + \"Update\");");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "return null;");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine("");

                    //Writes the DELETE function
                    sb.AppendLine(tab + tab + "static public bool Delete(int id_)");
                    sb.AppendLine(tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + "try");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + types[0].Name + " context = new " + types[0].Name + "();");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "var query = from u in context." + types[i].Name + " where u.id_ == id_ select u;");
                    sb.AppendLine("");
                    sb.AppendLine(tab + tab + tab + tab + "if (query.Any())");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + tab + "context." + types[i].Name + ".DeleteOnSubmit(query.First());");
                    sb.AppendLine(tab + tab + tab + "return true;");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "catch (Exception error)");
                    sb.AppendLine(tab + tab + tab + "{");
                    sb.AppendLine(tab + tab + tab + tab + "Console.WriteLine(\"EXCEPTION!!! \" + \"Classe: \" + \"mdl_" + types[i].Name + "\" + \" Metódo: \" + \"Delete\");");
                    sb.AppendLine(tab + tab + tab + "}");
                    sb.AppendLine(tab + tab + tab + "return false;");
                    sb.AppendLine(tab + tab + "}");
                    sb.AppendLine(tab + "}");
                    sb.AppendLine("}");

                    //Save the code file
                    string filePath = dirName + " / " + "model_" + types[i].Name + ".cs";
                    File.WriteAllText(filePath, sb.ToString());

                }
            }
        }
    }
}
